# Task 1

**Step 1: Create the following three datasets in memory as Python data structures (lists of dictionaries)**

**Dataset A — A list of 8 user registration entries with fields: username, email, age, and signup_date. Include at least 2 entries with problems: one with an invalid email (missing @), one with age as a string instead of a number, and one with an empty username.**

In [29]:
entries = [
    {"username": "coder_jack", "email": "jack@example.com", "age": 24, "signup_date": "2026-01-15"},
    {"username": "marina_v", "email": "marina.v@webmail.org", "age": 31, "signup_date": "2026-01-18"},
    {"username": "alex_pro", "email": "alex.pro.gmail.com", "age": 22, "signup_date": "2026-01-20"},#false gmail
    {"username": "sunny_days", "email": "sunny@provider.net", "age": "twenty-five", "signup_date": "2026-02-02"}, #false age
    {"username": "", "email": "ghost@ink.com", "age": 40, "signup_date": "2026-02-10"}, #empty username
    {"username": "tech_guru", "email": "guru@techspace.io", "age": 29, "signup_date": "2026-02-12"},
    {"username": "luna_sky", "email": "luna@skyview.com", "age": 19, "signup_date": "2026-02-25"},
    {"username": "fitness_dan", "email": "dan@fitlife.com", "age": 35, "signup_date": "2026-03-01"}
]

**Dataset B — A list of 10 application log entries with fields: timestamp, service, level (INFO/WARNING/ERROR), and message. Include entries from at least 3 different services.**

In [30]:
app_logs = [
    {"timestamp": "2026-03-02 10:00:01", "service": "auth-service", "level": "INFO", "message": "User 'jdoe' logged in successfully."},
    {"timestamp": "2026-03-02 10:05:22", "service": "payment-api", "level": "WARNING", "message": "Latency increased: 450ms (threshold: 300ms)."},
    {"timestamp": "2026-03-02 10:10:15", "service": "inventory-db", "level": "ERROR", "message": "Connection timeout while fetching product ID 502."},
    {"timestamp": "2026-03-02 10:12:45", "service": "auth-service", "level": "INFO", "message": "Password reset token generated for user 'admin'."},
    {"timestamp": "2026-03-02 10:15:30", "service": "payment-api", "level": "ERROR", "message": "Stripe API returned 402: Payment Required."},
    {"timestamp": "2026-03-02 10:20:05", "service": "inventory-db", "level": "INFO", "message": "Database backup completed in 12s."},
    {"timestamp": "2026-03-02 10:25:55", "service": "auth-service", "level": "WARNING", "message": "Multiple failed login attempts detected from IP 192.168.1.45."},
    {"timestamp": "2026-03-02 10:30:12", "service": "payment-api", "level": "INFO", "message": "Refund processed for transaction #TRX-9921."},
    {"timestamp": "2026-03-02 10:35:40", "service": "inventory-db", "level": "ERROR", "message": "Disk space critical: 98% usage on /var/lib/mysql."},
    {"timestamp": "2026-03-02 10:40:00", "service": "auth-service", "level": "INFO", "message": "Global session timeout policy updated."}
]

**Dataset C — A list of 6 product inventory records with fields: sku, product_name, quantity_in_stock, warehouse_location, and last_updated**

In [31]:
inventory_records = [
    {
        "sku": "SKU-1001-BLU", 
        "product_name": "Ergonomic Office Chair", 
        "quantity_in_stock": 150, 
        "warehouse_location": "A-12-04", 
        "last_updated": "2026-03-01 09:15:00"
    },
    {
        "sku": "SKU-2045-RED", 
        "product_name": "Mechanical Keyboard G5", 
        "quantity_in_stock": 42, 
        "warehouse_location": "B-03-11", 
        "last_updated": "2026-03-01 14:30:22"
    },
    {
        "sku": "SKU-8892-GRY", 
        "product_name": "Ultra-Wide Monitor 34\"", 
        "quantity_in_stock": 8, 
        "warehouse_location": "A-01-02", 
        "last_updated": "2026-03-02 08:05:10"
    },
    {
        "sku": "SKU-3310-BLK", 
        "product_name": "Wireless Noise Cancelling Headphones", 
        "quantity_in_stock": 215, 
        "warehouse_location": "C-05-09", 
        "last_updated": "2026-02-28 17:45:00"
    },
    {
        "sku": "SKU-5561-WHT", 
        "product_name": "Smart Home Hub v2", 
        "quantity_in_stock": 0, 
        "warehouse_location": "D-02-01", 
        "last_updated": "2026-03-02 11:20:45"
    },
    {
        "sku": "SKU-1122-MTL", 
        "product_name": "Aluminum Laptop Stand", 
        "quantity_in_stock": 89, 
        "warehouse_location": "B-08-15", 
        "last_updated": "2026-03-01 10:00:00"
    }
]

* Dataset A: User Registrations
Data Source Type: This represents User Input data.

Expected Quality Issues: In a production environment, this is often the "messiest" source. You can expect missing fields (empty usernames), incorrect data types (age entered as a string like "twenty-five" instead of an integer), and syntactically invalid strings (emails missing the "@" symbol or domain).

Validation for ML Pipeline: Before using this in an ML pipeline, I would apply Schema Validation to enforce data types, Regex (Regular Expression) checks to ensure email formats are valid, and Mandatory Field checks to drop or impute records with missing critical identifiers like usernames. *

* Dataset B: Application Logs
Data Source Type: This represents System-Generated data.

Expected Quality Issues: The primary issues here are usually structural drift (if a service updates its log format), timezone inconsistencies between different microservices, or missing entries due to network latency during high-traffic periods.

Validation for ML Pipeline: I would apply Timestamp Normalization to ensure all logs follow a consistent UTC format. I would also use Categorical Validation to ensure the level field only contains specific allowed values (INFO, WARNING, ERROR) and parse the message strings to extract structured features.*

* Dataset C: Product InventoryData Source Type: This represents an Internal Database (Records System).Expected Quality Issues: While usually cleaner than user input, the main issues are data staleness (the "last_updated" time might be old) and logical inconsistencies. For example, a quantity might be recorded as a negative number due to a synchronization error between the warehouse and the database.Validation for ML Pipeline: I would apply Range Checks (e.g., ensuring quantity_in_stock is $\ge 0$) and Referential Integrity checks to ensure the warehouse_location codes match known facility IDs. I would also flag records that haven't been updated within a specific timeframe to avoid training models on outdated stock levels. *

**Step 3: Write a validation function called validate_registrations(entries) that takes Dataset A and returns two lists: valid_entries and invalid_entries. A valid entry must have a non-empty username, an email containing @, and an age that can be converted to a positive integer. Test your function on Dataset A and print the counts.**

In [32]:

def validate_registrations(entries):
    valid_entries = []
    invalid_entries = []
    
    for entry in entries:
        username = str(entry.get("username", "")).strip()
        email = str(entry.get("email", ""))
        age_raw = entry.get("age")
        
        # Validation checks
        has_username = len(username) > 0
        has_at_symbol = "@" in email
        
        valid_age = False
        try:
            age = int(age_raw)
            if age > 0:
                valid_age = True
        except (ValueError, TypeError):
            valid_age = False
            
        if has_username and has_at_symbol and valid_age:
            valid_entries.append(entry)
        else:
            invalid_entries.append(entry)
            
    return valid_entries, invalid_entries

# Testing the function
valid, invalid = validate_registrations(user_registrations)

# Output the results
print(f"Valid entries count: {len(valid)}")
print(f"Invalid entries count: {len(invalid)}")

print("\n--- Invalid Entries ---")
for item in invalid:
    print(item)

Valid entries count: 5
Invalid entries count: 3

--- Invalid Entries ---
{'username': 'alex_pro', 'email': 'alex.pro.gmail.com', 'age': 22, 'signup_date': '2026-01-20'}
{'username': 'sunny_days', 'email': 'sunny@provider.net', 'age': 'twenty-five', 'signup_date': '2026-02-02'}
{'username': '', 'email': 'ghost@ink.com', 'age': 40, 'signup_date': '2026-02-10'}

# Task 2

**Step 1: Create a pandas DataFrame called rides with 500 rows and the following columns:**

In [33]:
import pandas as pd
import numpy as np

np.random.seed(13)
n_rows = 500

data = {
    "ride_id": np.arange(1, n_rows + 1),
    "driver_id": np.random.randint(1000, 1051, size=n_rows),
    "distance_km": np.round(np.random.uniform(1.0, 30.0, size=n_rows), 2),
    "fare_usd": np.round(np.random.uniform(5.0, 75.0, size=n_rows), 2),
    "ride_type": np.random.choice(["standard", "premium", "pool"], size=n_rows),
    "city": np.random.choice(["Berlin", "Seoul", "Nairobi", "Toronto", "Lima"], size=n_rows),
    "timestamp": pd.date_range(start="2025-01-01", periods=n_rows, freq="min")
}

rides = pd.DataFrame(data)

rides.head()

,ride_id,driver_id,distance_km,fare_usd,ride_type,city,timestamp
0,1,1018,22.10,24.90,pool,Berlin,2025-01-01 00:00:00
1,2,1048,22.02,39.92,premium,Seoul,2025-01-01 00:01:00
2,3,1010,19.48,71.91,pool,Toronto,2025-01-01 00:02:00
3,4,1016,10.84,17.67,pool,Seoul,2025-01-01 00:03:00
4,5,1038,7.50,71.89,premium,Lima,2025-01-01 00:04:00

**Step 2: Save the DataFrame in three formats:**

In [34]:
rides.to_csv("rides.csv", index=False)

rides.to_json("rides.json", orient="records", lines=True)

rides.to_parquet("rides.parquet", index=False)

**Step 3: Compare the file sizes of all three formats. Print the size of each file in KB and compute how many times smaller Parquet is compared to CSV.**

In [35]:
import os

csv_size = os.path.getsize("rides.csv") / 1024
json_size = os.path.getsize("rides.json") / 1024
parquet_size = os.path.getsize("rides.parquet") / 1024

ratio = csv_size / parquet_size

print(f"CSV File size: {csv_size:.2f} KB")
print(f"JSON File size: {json_size:.2f} KB")
print(f"Parquet File size: {parquet_size:.2f} KB")
print("-" * 30)
print(f"Result: Parquet is {ratio:.2f} times smaller than CSV.")

CSV File size: 27.13 KB
JSON File size: 64.66 KB
Parquet File size: 17.38 KB
------------------------------
Result: Parquet is 1.56 times smaller than CSV.

**Step 4: Read each file back into a new DataFrame and verify that the data is identical by comparing shapes and a sample of values. Note any differences you observe (for example, type changes after reading from CSV).**

In [36]:
# Reading the files back
rides_csv = pd.read_csv("rides.csv")
rides_json = pd.read_json("rides.json", orient="records", lines=True)
rides_parquet = pd.read_parquet("rides.parquet")

# Verification
formats = {
    "CSV": rides_csv,
    "JSON": rides_json,
    "Parquet": rides_parquet
}

print(f"Original Shape: {rides.shape}\n")

for name, df in formats.items():
    print(f"--- Testing {name} ---")
    print(f"Shape Match: {df.shape == rides.shape}")
    
    # Check data type of the 'timestamp' column
    print(f"Timestamp Type: {df['timestamp'].dtype}")

    
    # Compare first row of 'fare_usd' to check for value consistency
    original_val = rides.iloc[0]['fare_usd']
    read_val = df.iloc[0]['fare_usd']
    print(f"Fare Value Match: {np.isclose(original_val, read_val)}")
    print("\n")

Original Shape: (500, 7)

--- Testing CSV ---
Shape Match: True
Timestamp Type: object
Fare Value Match: True


--- Testing JSON ---
Shape Match: True
Timestamp Type: datetime64[ns]
Fare Value Match: True


--- Testing Parquet ---
Shape Match: True
Timestamp Type: datetime64[ns]
Fare Value Match: True

**Step 5: Write a markdown cell summarizing: Which format preserved types most faithfully? Which was smallest? When would you choose each format?**

* Data Format Summary
Most Faithful Type Preservation: Parquet. It is the only format that natively saves the schema metadata, ensuring that datetime and numeric types stay exactly as they were without needing manual conversion.

Smallest Size: Parquet. It uses binary columnar compression, making it significantly more compact than text-based formats. *

* When to Choose Each Format?
Parquet: Best for ML Pipelines and Big Data. Choose this for high-performance production environments where speed and storage efficiency are priorities.

CSV: Best for Portability. Choose this when you need to open the file in Excel or share it with people who don't use Python.

JSON: Best for Web & Streaming. Choose this for APIs or logs where data might be nested or needs to be read sətir-sətir (line by line). *

# Task 3

**Step 1: Create a large DataFrame with 200,000 rows and 20 numeric columns (random float values). Name the columns feature_0 through feature_19**

**Step 2: Measure and compare the time for these two operations:**

In [49]:
import numpy as np

n_rows = 200000
n_cols = 20

%time data = np.random.randn(n_rows, n_cols)
column_names = [f"feature_{i}" for i in range(n_cols)]

CPU times: total: 62.5 ms
Wall time: 97.4 ms

In [50]:
%time df = pd.DataFrame(data, columns=column_names)

CPU times: total: 0 ns
Wall time: 201 μs

In [53]:
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19
0,0.248942,-0.794344,0.663487,0.371440,1.444185,0.522559,-0.146487,0.837038,-0.237451,1.088637,-1.653287,-1.027777,0.876934,-0.110947,-0.099578,0.897644,-0.310471,0.133083,-0.522773,-0.232107
1,-1.099737,1.451976,-0.011228,0.982702,-0.705616,-0.364155,-0.912768,0.840423,-0.134140,-0.297900,0.256052,-0.669332,0.249344,-0.295692,-0.350294,-0.487639,1.089908,0.484853,-0.362342,0.008122
2,-0.809844,0.114437,0.584557,1.116914,0.949532,-0.279724,-0.627359,0.435376,-0.115061,1.021924,-0.121751,-1.541351,-0.010693,-0.366310,0.169247,-0.024860,0.372232,-1.542441,0.174751,1.322079
3,-0.505336,0.291292,-0.504630,-0.702082,0.451023,-1.489851,-0.188135,-0.169066,0.499914,1.016244,0.128490,0.999117,-1.971238,0.340882,-0.919959,-0.223073,0.405495,-0.808379,-1.562064,-0.095990
4,0.018694,-1.114285,1.034583,0.166812,2.211917,0.597125,0.446027,-0.738467,0.383094,0.032433,-1.144031,-0.907085,-0.078741,-0.992584,0.742561,0.673911,-1.238465,0.514081,-0.051084,0.068495

**Operation A — Column access: Compute the mean of feature_0 using the pandas column accessor (df["feature_0"].mean()**

In [52]:
df["feature_0"].mean()

np.float64(-0.0033744179500491203)

**Operation B — Row iteration: Loop through the first 10,000 rows using df.iloc[i] and sum the values of feature_0 manually.**

In [59]:
sm=0
for i in range (10_000):
    sm+=df.iloc[i]['feature_0']
sm

np.float64(-16.230628537708117)

**Use %%timeit or %time to measure each. Record the results**

In [74]:
%timeit df["feature_0"].mean()

1.64 ms ± 81.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [64]:
%%timeit
sm=0
for i in range (10_000):
    sm+=df.iloc[i]['feature_0']
sm

202 ms ± 8.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Step 3: Now convert the DataFrame to a NumPy array and repeat both operations:**

**Operation C — NumPy column access: Compute the mean of column 0 (arr[:, 0].mean()).**

**Operation D — NumPy row access: Access the first 10,000 rows sequentially (arr[i] in a loop) and sum column 0.**

In [65]:
arr = df.to_numpy()

In [73]:
%timeit arr[:, 0].mean()

686 μs ± 57.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [72]:
%%timeit
sm=0
for i in range (10_000):
    sm+=arr[i][0]
sm

2.43 ms ± 304 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

* Column access in pandas is much faster than row iteration because it uses vectorized operations backed by optimized NumPy code in C, avoiding slow Python loops. In contrast, row iteration with .iloc involves repeated indexing and Python-level overhead.*

* The gap becomes smaller with NumPy because NumPy arrays are simpler and do not include extra metadata like pandas DataFrames. Element access in NumPy is closer to raw memory, so even manual loops are faster*

* This shows that both libraries store data in contiguous, column-oriented memory, which makes column operations efficient. However, pandas adds abstraction (labels and indexing), which increases overhead during row-wise operations.*

# Task 4

**Step 1: Create a DataFrame with 100,000 rows and 5 numeric columns of random float values (use np.random.seed(42) for reproducibility). Add one string column called category with values randomly chosen from ["alpha", "beta", "gamma"].**

In [75]:
import pandas as pd
import numpy as np

np.random.seed(42)

num_rows = 100_000

data = {
    'col1': np.random.rand(num_rows),
    'col2': np.random.rand(num_rows),
    'col3': np.random.rand(num_rows),
    'col4': np.random.rand(num_rows),
    'col5': np.random.rand(num_rows)
}

In [76]:
df = pd.DataFrame(data)

categories = ["alpha", "beta", "gamma"]
df['category'] = np.random.choice(categories, size=num_rows)

print(df.head())

       col1      col2      col3      col4      col5 category
0  0.374540  0.580779  0.282588  0.157054  0.888953    alpha
1  0.950714  0.526972  0.458677  0.095509  0.315713    gamma
2  0.731994  0.351037  0.099215  0.137939  0.051910     beta
3  0.598658  0.493213  0.446837  0.473489  0.919744    alpha
4  0.156019  0.365097  0.203081  0.884534  0.436261    gamma

**Step 2: Save as CSV and Parquet. Compare file sizes.**

In [ ]:
import os

In [77]:
df.to_csv('data.csv', index=False)

df.to_parquet('data.parquet', index=False)

csv_size = os.path.getsize('data.csv') / (1024 * 1024)  # Convert to MB
parquet_size = os.path.getsize('data.parquet') / (1024 * 1024)

In [78]:
print(f"CSV File Size: {csv_size:.2f} MB")
print(f"Parquet File Size: {parquet_size:.2f} MB")

CSV File Size: 9.82 MB
Parquet File Size: 4.81 MB

**Step 3: Read the CSV back and check the dtypes. Then read the Parquet back and check the dtypes. Write a markdown cell explaining any differences you observe in how types were preserved.**

In [79]:
df_csv = pd.read_csv('data.csv')
print("--- CSV Data Types ---")
print(df_csv.dtypes)

--- CSV Data Types ---
col1        float64
col2        float64
col3        float64
col4        float64
col5        float64
category     object
dtype: object

In [81]:
df_parquet = pd.read_parquet('data.parquet')
print("\n--- Parquet Data Types ---")
print(df_parquet.dtypes)

--- Parquet Data Types ---
col1        float64
col2        float64
col3        float64
col4        float64
col5        float64
category     object
dtype: object

**Step 4: Perform a timing comparison: measure how long it takes to read the full dataset from CSV versus from Parquet. Record both times.**

In [82]:
%time pd.read_csv('data.csv')

CPU times: total: 93.8 ms
Wall time: 85.7 ms

           col1      col2      col3      col4      col5 category
0      0.374540  0.580779  0.282588  0.157054  0.888953    alpha
1      0.950714  0.526972  0.458677  0.095509  0.315713    gamma
2      0.731994  0.351037  0.099215  0.137939  0.051910     beta
3      0.598658  0.493213  0.446837  0.473489  0.919744    alpha
4      0.156019  0.365097  0.203081  0.884534  0.436261    gamma
...         ...       ...       ...       ...       ...      ...
99995  0.792305  0.622150  0.092811  0.750148  0.665520    alpha
99996  0.779253  0.629221  0.625631  0.272528  0.989442    gamma
99997  0.674453  0.192204  0.626662  0.575589  0.487741    alpha
99998  0.499447  0.653083  0.047650  0.893340  0.664987    alpha
99999  0.389908  0.001560  0.704077  0.502423  0.626668    alpha

[100000 rows x 6 columns]

In [83]:
%time pd.read_parquet('data.parquet')

CPU times: total: 15.6 ms
Wall time: 11.3 ms

           col1      col2      col3      col4      col5 category
0      0.374540  0.580779  0.282588  0.157054  0.888953    alpha
1      0.950714  0.526972  0.458677  0.095509  0.315713    gamma
2      0.731994  0.351037  0.099215  0.137939  0.051910     beta
3      0.598658  0.493213  0.446837  0.473489  0.919744    alpha
4      0.156019  0.365097  0.203081  0.884534  0.436261    gamma
...         ...       ...       ...       ...       ...      ...
99995  0.792305  0.622150  0.092811  0.750148  0.665520    alpha
99996  0.779253  0.629221  0.625631  0.272528  0.989442    gamma
99997  0.674453  0.192204  0.626662  0.575589  0.487741    alpha
99998  0.499447  0.653083  0.047650  0.893340  0.664987    alpha
99999  0.389908  0.001560  0.704077  0.502423  0.626668    alpha

[100000 rows x 6 columns]

**Step 5: Parquet supports reading only specific columns without loading the entire file. Read only the category column from the Parquet file and time it. Compare to reading the full file. Write a markdown cell explaining why this selective read is possible with Parquet but not with CSV.**

# Task 5

**Step 1: Create a flat (denormalized) DataFrame representing an online bookstore with at least 12 rows. Include columns: title, author, format (Paperback/E-book), publisher_name, publisher_country, price. Make sure at least two books have multiple formats (so the publisher info is repeated).**

In [89]:
import pandas as pd

data = {
    "title": [
        "The Great Gatsby", "The Great Gatsby", "1984", "1984", 
        "Brave New World", "The Hobbit", "Foundation", "Dune", 
        "Neuromancer", "Snow Crash", "The Alchemist", "Beloved"
    ],
    "author": [
        "F. Scott Fitzgerald", "F. Scott Fitzgerald", "George Orwell", "George Orwell",
        "Aldous Huxley", "J.R.R. Tolkien", "Isaac Asimov", "Frank Herbert",
        "William Gibson", "Neal Stephenson", "Paulo Coelho", "Toni Morrison"
    ],
    "format": [
        "Paperback", "E-book", "Paperback", "E-book", 
        "Paperback", "Paperback", "E-book", "Paperback", 
        "E-book", "Paperback", "Paperback", "Paperback"
    ],
    "publisher_name": [
        "Scribner", "Scribner", "Secker & Warburg", "Secker & Warburg",
        "Chatto & Windus", "Allen & Unwin", "Gnome Press", "Chilton Books",
        "Ace Books", "Bantam Books", "HarperCollins", "Alfred A. Knopf"
    ],
    "publisher_country": [
        "USA", "USA", "UK", "UK",
        "UK", "UK", "USA", "USA",
        "USA", "USA", "USA", "USA"
    ],
    "price": [
        15.99, 9.99, 12.50, 7.99, 
        14.00, 20.00, 8.50, 25.00, 
        6.99, 18.00, 13.99, 16.50
    ]
}

df_flat = pd.DataFrame(data)

df_flat.head()

,title,author,format,publisher_name,publisher_country,price
0,The Great Gatsby,F. Scott Fitzgerald,Paperback,Scribner,USA,15.99
1,The Great Gatsby,F. Scott Fitzgerald,E-book,Scribner,USA,9.99
2,1984,George Orwell,Paperback,Secker & Warburg,UK,12.50
3,1984,George Orwell,E-book,Secker & Warburg,UK,7.99
4,Brave New World,Aldous Huxley,Paperback,Chatto & Windus,UK,14.00

**Step 2: Create a normalized version of the same data using two DataFrames: books with columns: title, author,format,publisher_id, price publishers with columns: publisher_id, publisher_name, publisher_country**

In [90]:
import pandas as pd

publishers_data = {
    "publisher_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "publisher_name": [
        "Scribner", "Secker & Warburg", "Chatto & Windus", 
        "Allen & Unwin", "Gnome Press", "Chilton Books", 
        "Ace Books", "Bantam Books", "HarperCollins", "Alfred A. Knopf"
    ][:8], # Matching our 12-row book logic
    "publisher_country": ["USA", "UK", "UK", "UK", "USA", "USA", "USA", "USA"]
}
df_publishers = pd.DataFrame(publishers_data)

books_data = {
    "title": [
        "The Great Gatsby", "The Great Gatsby", "1984", "1984", 
        "Brave New World", "The Hobbit", "Foundation", "Dune", 
        "Neuromancer", "Snow Crash", "The Alchemist", "Beloved"
    ],
    "author": [
        "F. Scott Fitzgerald", "F. Scott Fitzgerald", "George Orwell", "George Orwell",
        "Aldous Huxley", "J.R.R. Tolkien", "Isaac Asimov", "Frank Herbert",
        "William Gibson", "Neal Stephenson", "Paulo Coelho", "Toni Morrison"
    ],
    "format": [
        "Paperback", "E-book", "Paperback", "E-book", 
        "Paperback", "Paperback", "E-book", "Paperback", 
        "E-book", "Paperback", "Paperback", "Paperback"
    ],
    "publisher_id": [1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "price": [
        15.99, 9.99, 12.50, 7.99, 
        14.00, 20.00, 8.50, 25.00, 
        6.99, 18.00, 13.99, 16.50
    ]
}

df_normalized = pd.DataFrame(books_data)

print("--- Publishers Table ---")
print(df_publishers.head(3))
print("\n--- Books Table ---")
print(df_normalized.head(3))

--- Publishers Table ---
   publisher_id    publisher_name publisher_country
0             1          Scribner               USA
1             2  Secker & Warburg                UK
2             3   Chatto & Windus                UK

--- Books Table ---
              title               author     format  publisher_id  price
0  The Great Gatsby  F. Scott Fitzgerald  Paperback             1  15.99
1  The Great Gatsby  F. Scott Fitzgerald     E-book             1   9.99
2              1984        George Orwell  Paperback             2  12.50

**Step 3: Create a document-oriented version of the same data as a list of dictionaries (JSON-style), where each book is a document containing nested publisher information and a list of editions.**

In [87]:
bookstore_documents = [
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publisher": {
            "name": "Scribner",
            "country": "USA"
        },
        "editions": [
            {"format": "Paperback", "price": 15.99},
            {"format": "E-book", "price": 9.99}
        ]
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "publisher": {
            "name": "Secker & Warburg",
            "country": "UK"
        },
        "editions": [
            {"format": "Paperback", "price": 12.50},
            {"format": "E-book", "price": 7.99}
        ]
    },
    {
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "publisher": {"name": "Chatto & Windus", "country": "UK"},
        "editions": [{"format": "Paperback", "price": 14.00}]
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publisher": {"name": "Allen & Unwin", "country": "UK"},
        "editions": [{"format": "Paperback", "price": 20.00}]
    }
    # ... and so on for the remaining books
]

# Example: Accessing nested data
print(f"Book: {bookstore_documents[0]['title']}")
print(f"First Edition Price: ${bookstore_documents[0]['editions'][0]['price']}")

Book: The Great Gatsby
First Edition Price: $15.99

**Step 4: For each representation (flat, normalized, document), write and execute code to answer these three questions:
What are all books by a specific author?
What is the average price across all editions?
Update a publisher's country (simulate the publisher moving to a new country). How many records/documents need to change?**

In [92]:

orwell_books_flat = df_flat[df_flat['author'] == "George Orwell"]


avg_price_flat = df_flat['price'].mean()


rows_to_update = df_flat[df_flat['publisher_name'] == "Scribner"].shape[0]
df_flat.loc[df_flat['publisher_name'] == "Scribner", 'publisher_country'] = "Canada"

print(f"Flat - Average Price: ${avg_price_flat:.2f}")
print(f"Flat - Rows updated for Scribner: {rows_to_update}")

Flat - Average Price: $14.12
Flat - Rows updated for Scribner: 2

In [93]:

orwell_books_norm = df_normalized[df_normalized['author'] == "George Orwell"]
avg_price_norm = df_normalized['price'].mean()
pub_mask = df_publishers['publisher_name'] == "Scribner"
df_publishers.loc[pub_mask, 'publisher_country'] = "Canada"
records_updated = pub_mask.sum()

print(f"Normalized - Average Price: ${avg_price_norm:.2f}")
print(f"Normalized - Records updated in Publisher table: {records_updated}")

Normalized - Average Price: $14.12
Normalized - Records updated in Publisher table: 1

In [95]:
orwell_docs = [doc for doc in bookstore_documents if doc['author'] == "George Orwell"]
all_prices = [ed['price'] for doc in bookstore_documents for ed in doc['editions']]
avg_price_doc = sum(all_prices) / len(all_prices)
docs_updated = 0
for doc in bookstore_documents:
    if doc['publisher']['name'] == "Scribner":
        doc['publisher']['country'] = "Canada"
        docs_updated += 1

print(f"Document - Average Price: ${avg_price_doc:.2f}")
print(f"Document - Documents updated: {docs_updated}")

Document - Average Price: $13.41
Document - Documents updated: 1

* 1. Which representation made the answer easiest?
Finding books by author: Flat (Step 1) and Normalized (Step 2) were the easiest. A simple one-line Pandas filter df[df['author'] == '...'] is much more intuitive than the list comprehensions or loops required for the Document model.

Calculating Average Price: Flat and Normalized were again the winners. Because they store prices in a single column, we can use the high-performance .mean() method. In the Document model, we had to "flatten" the nested editions manually before calculating. *

 * 2. Frequent Publisher Changes?
If publisher information (like country or name) changes frequently, the Normalized (Step 2) representation is the superior choice.

Why? It follows the "Single Source of Truth" principle. You only have to update one record in the publishers table.

In the Flat and Document models, you have to find and update every single occurrence of that publisher across thousands of rows or documents, which risks data inconsistency (e.g., updating some rows but missing others). *

* 3. Accessing Books as Standalone Records?
If your primary use case is a website where users click on a book to see all its details (title, author, publisher, and all available prices), the Document (Step 3) representation is the best choice.

Why? All the data needed for that specific book is bundled together in one "document."

In a Normalized system, you would have to perform a "Join" (merging tables) every single time a page loads, which can become a performance bottleneck at scale.*